import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
})
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
})

const eudoxus = localFont({
    src: './fonts/EudoxusSansGX.woff',
    variable: '--font-eudoxus-sans',
    weight: '100 900',
})

const eudoxus2 = localFont({
    src: './fonts/EudoxusSansGX.woff2',
    variable: '--font-eudoxus-sans-2',
    weight: '100 900',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${eudoxus.variable} ${eudoxus2.variable}`}>
                {children}
            </body>
        </html>
    )
}
